---
# tasks file for role_nagios
- name: Remove Docker-ce repository
  yum_repository:
    name: docker-ce
    description: Docker-CE CentOS repo
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    state: absent

- name: Uninstall docker-CE
  yum:
    name: docker*
    state: absent
    autoremove: yes

