---
# tasks file for role_nagios
- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker-CE CentOS repo
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Uninstall docker
  yum:
    name: docker
    state: absent
    autoremove: yes

- name: Install docker-ce to the latest version
  yum:
    name: docker-ce
    state: latest

- name: Start and enable Docker systemct service
  service:
    name: docker
    state: started
    enabled: yes

